# Generated by Django 3.1.6 on 2021-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='car name')),
                ('total', models.PositiveIntegerField(blank=True, verbose_name='total cars')),
                ('total_price', models.PositiveIntegerField(blank=True, verbose_name='total price')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('cars', models.ManyToManyField(related_name='cars', to='cars.Car', verbose_name='cars')),
            ],
        ),
    ]
