# Generated by Django 3.1.6 on 2021-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('orders', '0004_auto_20210204_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(to='cars.Car', verbose_name='cars'),
        ),
    ]
