# Generated by Django 3.2.3 on 2021-05-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='order description')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='total cars')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='total price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('cars', models.ManyToManyField(to='cars.Car', verbose_name='cars')),
            ],
        ),
    ]
